name: 'voting_analytics'
version: '1.0.0'
config-version: 2

# Directory structure
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  voting_analytics:
    # Config for all models
    +materialized: view
    
    staging:
      +materialized: view
      +schema: staging
    
    marts:
      +materialized: table
      +schema: marts